# Generated by Django 5.2.7 on 2025-11-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='tag',
            new_name='tags',
        ),
    ]
