# Generated by Django 5.2.7 on 2025-12-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_comment_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("lesson", "user")},
        ),
    ]
